import type { Salon, ServiceCategory } from "@/app/lib/marketplace-data";

export const fallbackMarketplaceData = {
  serviceCategories: [
    {
      name: "Hair Studio",
      slug: "Hair Studio",
      detail: "Color, cuts, spa and care routines",
      price: "from Rs. 699",
      tone: "bg-[#fce4ec]",
    },
    {
      name: "Bridal Beauty",
      slug: "Bridal Beauty",
      detail: "Trials, makeup, draping and packages",
      price: "from Rs. 4,999",
      tone: "bg-[#f9dfd0]",
    },
    {
      name: "Skin & Facial",
      slug: "Skin & Facial",
      detail: "Glow facials, cleanups and skin care",
      price: "from Rs. 899",
      tone: "bg-[#dff3ed]",
    },
    {
      name: "Nails & Spa",
      slug: "Nails & Spa",
      detail: "Gel nails, manicure and spa therapy",
      price: "from Rs. 599",
      tone: "bg-[#e8e1f5]",
    },
  ],
  salons: [
    {
      id: "aster-glow",
      name: "Aster Glow Studio",
      area: "Bandra West",
      coords: { lat: 19.0596, lng: 72.8295 },
      categories: ["Bridal Beauty", "Hair Studio", "Skin & Facial", "Nails & Spa"],
      rating: 4.9,
      reviews: 412,
      basePrice: 1299,
      distanceKm: 1.8,
      responseMins: 12,
      hygieneScore: 98,
      homeVisit: false,
      bridalReady: true,
      luxury: true,
      slots: ["10:30 AM", "12:45 PM", "4:30 PM", "6:00 PM"],
      tags: ["AI Match", "Luxury color", "Hygiene verified"],
      specialty: "Luxury hair color, skin prep and glow treatments.",
    },
    {
      id: "mira-bridal",
      name: "Mira Bridal Bar",
      area: "Juhu",
      coords: { lat: 19.1075, lng: 72.8263 },
      categories: ["Bridal Beauty", "Hair Studio", "Skin & Facial"],
      rating: 4.8,
      reviews: 335,
      basePrice: 5499,
      distanceKm: 4.2,
      responseMins: 18,
      hygieneScore: 96,
      homeVisit: true,
      bridalReady: true,
      luxury: true,
      slots: ["11:00 AM", "2:30 PM", "7:15 PM"],
      tags: ["Bride Pick", "Trial available", "Home visit"],
      specialty: "Bridal makeup, draping, trials and pre-wedding care.",
    },
    {
      id: "mint-home",
      name: "Mint Home Salon",
      area: "Powai",
      coords: { lat: 19.1176, lng: 72.906 },
      categories: ["Skin & Facial", "Nails & Spa"],
      rating: 4.7,
      reviews: 286,
      basePrice: 899,
      distanceKm: 7.4,
      responseMins: 9,
      hygieneScore: 94,
      homeVisit: true,
      bridalReady: false,
      luxury: false,
      slots: ["9:30 AM", "1:00 PM", "5:45 PM", "8:00 PM"],
      tags: ["Home Visit", "Fast response", "Value pick"],
      specialty: "At-home facials, waxing, manicure and pedicure.",
    },
    {
      id: "opal-nails",
      name: "Opal Nail Atelier",
      area: "Lower Parel",
      coords: { lat: 18.993, lng: 72.8304 },
      categories: ["Nails & Spa"],
      rating: 4.6,
      reviews: 198,
      basePrice: 749,
      distanceKm: 3.1,
      responseMins: 24,
      hygieneScore: 95,
      homeVisit: false,
      bridalReady: false,
      luxury: true,
      slots: ["12:15 PM", "3:00 PM", "5:30 PM"],
      tags: ["Gel nails", "Spa chairs", "Premium finish"],
      specialty: "Gel extensions, nail art, foot spa and hand care.",
    },
    {
      id: "saffron-men",
      name: "Saffron Grooming Co.",
      area: "Andheri East",
      coords: { lat: 19.1155, lng: 72.8727 },
      categories: ["Hair Studio", "Skin & Facial"],
      rating: 4.5,
      reviews: 221,
      basePrice: 699,
      distanceKm: 6.5,
      responseMins: 15,
      hygieneScore: 92,
      homeVisit: false,
      bridalReady: false,
      luxury: false,
      slots: ["10:00 AM", "1:45 PM", "6:30 PM"],
      tags: ["Grooming", "Express facial", "Budget friendly"],
      specialty: "Haircuts, beard styling, detan and express facials.",
    },
    {
      id: "pearl-luxe",
      name: "Pearl Luxe Salon",
      area: "Colaba",
      coords: { lat: 18.9067, lng: 72.8147 },
      categories: ["Bridal Beauty", "Hair Studio", "Nails & Spa"],
      rating: 4.9,
      reviews: 501,
      basePrice: 2499,
      distanceKm: 8.1,
      responseMins: 28,
      hygieneScore: 99,
      homeVisit: true,
      bridalReady: true,
      luxury: true,
      slots: ["2:00 PM", "4:00 PM"],
      tags: ["Celebrity stylists", "Luxury suite", "Group booking"],
      specialty: "Premium bridal, party styling and luxury nail care.",
    },
    {
      id: "fort-rose",
      name: "Fort Rose Beauty House",
      area: "Fort",
      coords: { lat: 18.9338, lng: 72.8346 },
      categories: ["Hair Studio", "Skin & Facial"],
      rating: 4.6,
      reviews: 184,
      basePrice: 999,
      distanceKm: 9.4,
      responseMins: 20,
      hygieneScore: 94,
      homeVisit: false,
      bridalReady: false,
      luxury: false,
      slots: ["10:15 AM", "1:30 PM", "5:15 PM"],
      tags: ["Office ready", "Cleanup", "Hair care"],
      specialty: "Workday hair styling, glow cleanups and express facials.",
    },
    {
      id: "churchgate-chic",
      name: "Churchgate Chic Studio",
      area: "Churchgate",
      coords: { lat: 18.9352, lng: 72.8271 },
      categories: ["Hair Studio", "Nails & Spa"],
      rating: 4.7,
      reviews: 246,
      basePrice: 1199,
      distanceKm: 9.1,
      responseMins: 17,
      hygieneScore: 95,
      homeVisit: false,
      bridalReady: false,
      luxury: true,
      slots: ["11:30 AM", "3:15 PM", "6:45 PM"],
      tags: ["Blow dry", "Gel polish", "Premium tools"],
      specialty: "Hair styling, nail polish, party-ready blowouts and spa care.",
    },
    {
      id: "marine-glow",
      name: "Marine Glow Lounge",
      area: "Marine Lines",
      coords: { lat: 18.944, lng: 72.8236 },
      categories: ["Skin & Facial", "Bridal Beauty"],
      rating: 4.8,
      reviews: 302,
      basePrice: 1799,
      distanceKm: 8.7,
      responseMins: 16,
      hygieneScore: 97,
      homeVisit: true,
      bridalReady: true,
      luxury: true,
      slots: ["10:45 AM", "2:15 PM", "7:00 PM"],
      tags: ["Glow facial", "Bride prep", "Home visit"],
      specialty: "Pre-event skin prep, bridal glow routines and home facials.",
    },
    {
      id: "tardeo-tone",
      name: "Tardeo Tone Salon",
      area: "Tardeo",
      coords: { lat: 18.9676, lng: 72.8141 },
      categories: ["Hair Studio", "Skin & Facial"],
      rating: 4.5,
      reviews: 168,
      basePrice: 899,
      distanceKm: 7.3,
      responseMins: 22,
      hygieneScore: 93,
      homeVisit: false,
      bridalReady: false,
      luxury: false,
      slots: ["9:45 AM", "12:30 PM", "4:45 PM"],
      tags: ["Detan", "Hair spa", "Value pick"],
      specialty: "Hair spa, detan, cleanups and everyday grooming packages.",
    },
    {
      id: "mahalaxmi-muse",
      name: "Mahalaxmi Muse",
      area: "Mahalaxmi",
      coords: { lat: 18.9822, lng: 72.8249 },
      categories: ["Bridal Beauty", "Hair Studio", "Nails & Spa"],
      rating: 4.8,
      reviews: 356,
      basePrice: 3299,
      distanceKm: 5.9,
      responseMins: 18,
      hygieneScore: 97,
      homeVisit: true,
      bridalReady: true,
      luxury: true,
      slots: ["11:15 AM", "3:45 PM", "6:30 PM"],
      tags: ["Bride trial", "Party styling", "Premium suite"],
      specialty: "Bridal trials, luxury styling, makeup and nail packages.",
    },
    {
      id: "worli-waves",
      name: "Worli Waves Salon",
      area: "Worli",
      coords: { lat: 19.0176, lng: 72.8162 },
      categories: ["Hair Studio", "Nails & Spa"],
      rating: 4.6,
      reviews: 211,
      basePrice: 1099,
      distanceKm: 4.5,
      responseMins: 19,
      hygieneScore: 94,
      homeVisit: false,
      bridalReady: false,
      luxury: true,
      slots: ["10:00 AM", "2:00 PM", "5:30 PM"],
      tags: ["Hair color", "Foot spa", "Sea link area"],
      specialty: "Hair color, nail care, foot spa and weekend styling.",
    },
  ],
} satisfies {
  serviceCategories: ServiceCategory[];
  salons: Salon[];
};
